
import { Category, Quote } from './types';

export const CATEGORIES: Category[] = [
  { id: 'sucesso', name: 'Sucesso', icon: '🏆', description: 'Alcance seus objetivos mais altos.', color: 'from-amber-400 to-orange-500' },
  { id: 'resiliencia', name: 'Resiliência', icon: '⚓', description: 'Mantenha-se firme nas tempestades.', color: 'from-blue-500 to-indigo-600' },
  { id: 'disciplina', name: 'Disciplina', icon: '⚔️', description: 'O caminho para a maestria.', color: 'from-slate-700 to-slate-900' },
  { id: 'mentalidade', name: 'Mentalidade', icon: '🧠', description: 'Transforme seus pensamentos.', color: 'from-emerald-400 to-teal-600' },
  { id: 'gratidao', name: 'Gratidão', icon: '✨', description: 'Aprecie a jornada.', color: 'from-rose-400 to-pink-500' },
  { id: 'trabalho', name: 'Carreira', icon: '💼', description: 'Evolução profissional constante.', color: 'from-violet-500 to-purple-700' },
  { id: 'lideranca', name: 'Liderança', icon: '👑', description: 'Inspire e guie outros para a grandeza.', color: 'from-amber-600 to-yellow-800' },
  { id: 'foco', name: 'Foco', icon: '🎯', description: 'Clareza total no que realmente importa.', color: 'from-cyan-500 to-blue-700' },
];

const generateQuotes = (cat: string, baseQuotes: {t: string, a: string}[]): Quote[] => {
  return baseQuotes.map((q, i) => ({
    id: `${cat}-${i}`,
    text: q.t,
    author: q.a,
    category: cat
  }));
};

const sucessoData = [
  { t: "O sucesso não é o fim, o fracasso não é fatal: o que conta é a coragem de continuar.", a: "Winston Churchill" },
  { t: "Não espere por oportunidades, crie-as.", a: "Anônimo" },
  { t: "O sucesso é a soma de pequenos esforços repetidos dia após dia.", a: "Robert Collier" },
  { t: "Para ter sucesso, o seu desejo de sucesso deve ser maior do que o seu medo de falhar.", a: "Bill Cosby" },
  { t: "Defina o sucesso em seus próprios termos, alcance-o por suas próprias regras.", a: "Anne Sweeney" },
  { t: "O caminho para o sucesso e o caminho para o fracasso são quase exatamente os mesmos.", a: "Colin Davis" },
  { t: "O sucesso normalmente vem para quem está ocupado demais para procurar por ele.", a: "Henry David Thoreau" },
  { t: "O segredo do sucesso é a constância do propósito.", a: "Benjamin Disraeli" },
  { t: "O sucesso não é a chave para a felicidade. A felicidade é a chave para o sucesso.", a: "Albert Schweitzer" },
  { t: "Sempre que você vê uma pessoa de sucesso, você vê apenas as glórias públicas, nunca os sacrifícios privados.", a: "Vaibhav Shah" },
  { t: "O sucesso consiste em ir de fracasso em fracasso sem perder o entusiasmo.", a: "Winston Churchill" },
  { t: "A única maneira de atingir o impossível é acreditar que é possível.", a: "Charles Kingsleigh" },
  { t: "O sucesso é gostar de si mesmo, gostar do que você faz e gostar de como você faz.", a: "Maya Angelou" },
  { t: "Tudo o que a mente humana pode conceber e acreditar, ela pode alcançar.", a: "Napoleon Hill" },
  { t: "Grandes mentes discutem ideias; mentes médias discutem eventos; mentes pequenas discutem pessoas.", a: "Eleanor Roosevelt" },
  { t: "Tente não ser uma pessoa de sucesso, mas sim uma pessoa de valor.", a: "Albert Einstein" },
  { t: "Não fui eu quem escolhi o sucesso, o sucesso me escolheu.", a: "Anônimo" },
  { t: "A medida real do seu sucesso é o número de vezes que você consegue se recuperar do fracasso.", a: "Stephen Richards" },
  { t: "Se você quer alcançar a excelência, pode chegar lá hoje.", a: "Thomas J. Watson" },
  { t: "O fracasso é o tempero que dá sabor ao sucesso.", a: "Truman Capote" },
  { t: "A vitória é mais doce quando você conheceu a derrota.", a: "Malcolm S. Forbes" },
  { t: "Vencer não é tudo, mas querer vencer é.", a: "Vince Lombardi" },
  { t: "O sucesso vem para aqueles que têm a coragem de tentar o novo.", a: "Anônimo" },
  { t: "Só se pode alcançar o sucesso através da falha repetida.", a: "Soichiro Honda" },
  { t: "O sucesso é o resultado da preparação e trabalho duro.", a: "Colin Powell" },
  { t: "Oportunidades não acontecem. Você as cria.", a: "Chris Grosser" },
  { t: "Se você quer ser bem-sucedido, precisa ter dedicação total.", a: "Pelé" },
  { t: "Não tenha medo de desistir do bom para ir atrás do ótimo.", a: "John D. Rockefeller" },
  { t: "O sucesso é um mestre terrível. Ele convence as pessoas inteligentes de que elas não podem perder.", a: "Bill Gates" },
  { t: "Ação é a chave fundamental para todo sucesso.", a: "Pablo Picasso" },
  { t: "O sucesso não é para os preguiçosos.", a: "Anônimo" },
  { t: "Grandes resultados exigem grandes ambições.", a: "Heráclito" },
  { t: "Não pare quando estiver cansado, pare quando tiver terminado.", a: "Anônimo" },
  { t: "O sucesso é a melhor vingança.", a: "Frank Sinatra" },
  { t: "A coragem é a primeira das qualidades humanas porque garante todas as outras.", a: "Aristóteles" },
  { t: "Onde há uma vontade, há um caminho.", a: "Anônimo" },
  { t: "O sucesso é 10% inspiração e 90% transpiração.", a: "Thomas Edison" },
  { t: "Nada no mundo substitui a persistência.", a: "Calvin Coolidge" },
  { t: "A confiança é o primeiro segredo do sucesso.", a: "Ralph Waldo Emerson" },
  { t: "As pessoas não planejam falhar, elas falham ao planejar.", a: "Benjamin Franklin" },
  { t: "Faça o que você puder, com o que você tem, onde você estiver.", a: "Theodore Roosevelt" },
  { t: "Comece onde você está. Use o que você tem. Faça o que puder.", a: "Arthur Ashe" },
  { t: "Dificuldades reais podem ser superadas; apenas as imaginárias são invencíveis.", a: "Theodore N. Vail" },
  { t: "Seja a mudança que você deseja ver no mundo.", a: "Mahatma Gandhi" },
  { t: "Se você pode sonhar, você pode fazer.", a: "Walt Disney" },
  { t: "Tudo o que você sempre quis está do outro lado do medo.", a: "George Addair" },
  { t: "A única pessoa que você está destinado a se tornar é a pessoa que você decide ser.", a: "Ralph Waldo Emerson" },
  { t: "O sucesso não tem a ver com quanto dinheiro você ganha, mas com a diferença que você faz.", a: "Michelle Obama" },
  { t: "Seus sonhos não têm data de validade.", a: "Anônimo" },
  { t: "O sucesso mora onde a preparação encontra a oportunidade.", a: "Sêneca" },
  { t: "Vá firme na direção das suas metas, porque o pensamento cria e o desejo atrai.", a: "Anônimo" },
  { t: "O sucesso é a jornada, não o destino.", a: "Anônimo" },
  { t: "Acredite em si mesmo e o resto virá naturalmente.", a: "Anônimo" },
  { t: "O melhor momento para plantar uma árvore foi há 20 anos. O segundo melhor é agora.", a: "Provérbio Chinês" },
  { t: "Quem tem um porquê para viver suporta quase qualquer como.", a: "Viktor Frankl" },
  { t: "A vida encolhe ou expande em proporção à sua coragem.", a: "Anaïs Nin" },
];

const resilienciaData = [
  { t: "A resiliência é a capacidade de enfrentar adversidades e sair delas mais forte.", a: "Nelson Mandela" },
  { t: "O mundo quebra a todos e, depois, muitos são fortes nos lugares quebrados.", a: "Ernest Hemingway" },
  { t: "Não sou o que me aconteceu, sou o que escolho me tornar.", a: "Carl Jung" },
  { t: "Caia sete vezes, levante-se oito.", a: "Provérbio Japonês" },
  { t: "O carvalho lutou contra o vento e quebrou, o salgueiro dobrou quando precisou e sobreviveu.", a: "Robert Jordan" },
  { t: "Nossa maior glória não reside em nunca cair, mas em levantarmo-nos toda vez que caímos.", a: "Confúcio" },
  { t: "A adversidade revela o gênio, a prosperidade o esconde.", a: "Horácio" },
  { t: "A vida não fica mais fácil, você apenas fica mais forte.", a: "Anônimo" },
  { t: "O que não nos mata, nos torna mais fortes.", a: "Friedrich Nietzsche" },
  { t: "As dificuldades preparam pessoas comuns para destinos extraordinários.", a: "C.S. Lewis" },
  { t: "Persistência é a irmã gêmea da excelência.", a: "Marabel Morgan" },
  { t: "A esperança é a única coisa mais forte que o medo.", a: "Anônimo" },
  { t: "O rio corta a rocha não por causa de sua força, mas por causa de sua persistência.", a: "James N. Watkins" },
  { t: "Onde não há luta, não há força.", a: "Oprah Winfrey" },
  { t: "Se você estiver atravessando o inferno, continue indo.", a: "Winston Churchill" },
  { t: "A dor é inevitável. O sofrimento é opcional.", a: "Buda" },
  { t: "Não importa o quão devagar você vá, desde que você não pare.", a: "Confúcio" },
  { t: "Um mar calmo nunca fez um marinheiro habilidoso.", a: "Provérbio Inglês" },
  { t: "Você nunca sabe o quão forte você é, até que ser forte seja sua única escolha.", a: "Bob Marley" },
  { t: "A resiliência é a arte de navegar em torrentes emocionais.", a: "Anônimo" },
  { t: "O diamante é apenas um pedaço de carvão que suportou uma pressão extraordinária.", a: "Anônimo" },
  { t: "Fique firme. O sol sempre volta a brilhar.", a: "Anônimo" },
  { t: "O revés é apenas um degrau para o retorno.", a: "Anônimo" },
  { t: "A vida te joga pedras, você decide se faz um muro ou uma ponte.", a: "Anônimo" },
  { t: "Ser forte não é a ausência de dor, mas o ato de prosseguir apesar dela.", a: "Anônimo" },
  { t: "Aguente firme. O que hoje é dor, amanhã será força.", a: "Anônimo" },
  { t: "Sua coragem deve ser maior que sua vontade de desistir.", a: "Anônimo" },
  { t: "Às vezes você precisa passar pelo pior para chegar ao melhor.", a: "Anônimo" },
  { t: "A tempestade é passageira, sua determinação é eterna.", a: "Anônimo" },
  { t: "Resiliência não é aguentar tudo, é saber recomeçar.", a: "Anônimo" },
  { t: "Não se deixe abater pelos dias cinzas.", a: "Anônimo" },
  { t: "Todo recomeço é uma nova chance de ser melhor.", a: "Anônimo" },
  { t: "A força não vem da capacidade física, vem de uma vontade indomável.", a: "Mahatma Gandhi" },
  { t: "O sucesso é cair sete vezes e levantar oito.", a: "Anônimo" },
  { t: "Seja como o bambu: vergue mas não quebre.", a: "Provérbio Chinês" },
  { t: "A superação é o oxigênio da alma.", a: "Anônimo" },
  { t: "Grandes batalhas só são dadas a grandes guerreiros.", a: "Anônimo" },
  { t: "Seja resiliente, o tempo de colheita virá.", a: "Anônimo" },
  { t: "Não foque na queda, foque no salto.", a: "Anônimo" },
  { t: "O caos é o solo onde a resiliência floresce.", a: "Anônimo" },
  { t: "Nunca é tarde para ser o que você poderia ter sido.", a: "George Eliot" },
  { t: "A cicatriz prova que você foi mais forte que o que tentou te ferir.", a: "Anônimo" },
  { t: "Acredite na sua luz interior mesmo na escuridão.", a: "Anônimo" },
  { t: "Resiliência é saber que a chuva limpa o caminho para o sol.", a: "Anônimo" },
  { t: "O seu limite é apenas onde a sua mente diz que é.", a: "Anônimo" },
  { t: "Não conte os dias, faça os dias contarem.", a: "Muhammad Ali" },
  { t: "O destino é para quem aceita, a conquista é para quem luta.", a: "Anônimo" },
  { t: "A paciência é a virtude dos fortes.", a: "Anônimo" },
  { t: "Você é o mestre do seu destino e capitão da sua alma.", a: "William Ernest Henley" },
  { t: "Lute sempre, vença às vezes, desista nunca.", a: "Anônimo" },
];

const disciplinaData = [
  { t: "Disciplina é escolher entre o que você quer agora e o que você mais quer.", a: "Abraham Lincoln" },
  { t: "Motivação é o que te faz começar. Hábito é o que te faz continuar.", a: "Jim Ryun" },
  { t: "A disciplina é a ponte entre metas e realizações.", a: "Jim Rohn" },
  { t: "O success é o resultado de uma pequena disciplina praticada todos os dias.", a: "Anônimo" },
  { t: "Sem disciplina, não há vitória.", a: "Provérbio Grego" },
  { t: "A disciplina é a alma de um exército.", a: "George Washington" },
  { t: "A liberdade só é possível através da autodisciplina.", a: "Anônimo" },
  { t: "O sofrimento da disciplina é menor que o sofrimento do arrependimento.", a: "Jim Rohn" },
  { t: "Disciplina é fazer o que precisa ser feito, mesmo quando você não quer.", a: "Anônimo" },
  { t: "Vença a si mesmo e o mundo será seu.", a: "Anônimo" },
  { t: "Hábitos são teias no início, mas cabos no fim.", a: "Provérbio Chinês" },
  { t: "A excelência não é um ato, mas um hábito.", a: "Aristóteles" },
  { t: "A constância é o fundamento da virtude.", a: "Francis Bacon" },
  { t: "A disciplina transforma o talento em habilidade.", a: "Anônimo" },
  { t: "Seja o seu próprio patrão na disciplina.", a: "Anônimo" },
  { t: "Disciplina é o ingrediente secreto dos mestres.", a: "Anônimo" },
  { t: "Não espere a vontade chegar, a disciplina chega antes.", a: "Anônimo" },
  { t: "A repetição é a mãe da maestria.", a: "Anônimo" },
  { t: "A disciplina é a base da autoconfiança.", a: "Anônimo" },
  { t: "Mantenha a rotina, o resultado virá.", a: "Anônimo" },
  { t: "Foco é dizer não às distrações.", a: "Steve Jobs" },
  { t: "A disciplina é o que te separa da multidão.", a: "Anônimo" },
  { t: "O corpo faz o que a mente manda.", a: "Anônimo" },
  { t: "Seja escravo dos seus bons hábitos.", a: "Anônimo" },
  { t: "A persistência mata a resistência.", a: "Anônimo" },
  { t: "O sucesso é construído à noite enquanto outros dormem.", a: "Anônimo" },
  { t: "O preço da grandeza é a responsabilidade.", a: "Winston Churchill" },
  { t: "Não negocie com a sua preguiça.", a: "Anônimo" },
  { t: "Seja implacável com suas metas e paciente com seus resultados.", a: "Anônimo" },
  { t: "Disciplina é liberdade.", a: "Jocko Willink" },
  { t: "Quem domina a si mesmo é maior que quem domina uma cidade.", a: "Provérbio Bíblico" },
  { t: "O trabalho duro bate o talento se o talento não trabalhar duro.", a: "Tim Notke" },
  { t: "A autodisciplina é o maior de todos os investimentos.", a: "Anônimo" },
  { t: "Crie sistemas, não apenas metas.", a: "James Clear" },
  { t: "A consistência é o que transforma o comum em extraordinário.", a: "Anônimo" },
  { t: "Pequenas vitórias diárias levam a grandes conquistas.", a: "Anônimo" },
  { t: "A disciplina é o que sustenta o seu propósito.", a: "Anônimo" },
  { t: "O hábito é a segunda natureza do homem.", a: "Anônimo" },
  { t: "Sua rotina hoje define seu futuro amanhã.", a: "Anônimo" },
  { t: "Não aceite desculpas de si mesmo.", a: "Anônimo" },
  { t: "Disciplina é a forma mais pura de amor-próprio.", a: "Anônimo" },
  { t: "Se você não se governar, outros o farão.", a: "Anônimo" },
  { t: "O segredo do seu sucesso é encontrado na sua agenda diária.", a: "John Maxwell" },
  { t: "A disciplina é a arte de focar no que realmente importa.", a: "Anônimo" },
  { t: "Treine enquanto eles dormem, estude enquanto eles se divertem.", a: "Anônimo" },
  { t: "A excelência é o resultado gradual de sempre querer fazer melhor.", a: "Pat Riley" },
  { t: "O esforço de hoje é o conforto de amanhã.", a: "Anônimo" },
  { t: "Não confie na motivação, confie na disciplina.", a: "Anônimo" },
  { t: "Você é o que você faz repetidamente.", a: "Aristóteles" },
  { t: "A disciplina cura a dúvida.", a: "Anônimo" },
];

const mentalidadeData = [
  { t: "Sua mente é sua ferramenta mais poderosa. Use-a bem.", a: "Anônimo" },
  { t: "O segredo da mudança é focar toda a sua energia no novo.", a: "Sócrates" },
  { t: "A vida é 10% o que acontece comigo e 90% como eu reajo.", a: "Charles Swindoll" },
  { t: "Mude seus pensamentos e você mudará seu mundo.", a: "Norman Vincent Peale" },
  { t: "Se você pensa que pode ou pensa que não pode, você está certo.", a: "Henry Ford" },
  { t: "Tudo o que somos é o resultado do que pensamos.", a: "Buda" },
  { t: "A mente que se abre a uma nova ideia jamais volta ao original.", a: "Albert Einstein" },
  { t: "Você se torna o que você acredita.", a: "Oprah Winfrey" },
  { t: "Não veja os problemas como obstáculos, veja-os como degraus.", a: "Anônimo" },
  { t: "Otimismo é a fé que leva à realização.", a: "Helen Keller" },
  { t: "A felicidade depende da qualidade de seus pensamentos.", a: "Marco Aurélio" },
  { t: "Imagine uma nova história para sua vida e acredite nela.", a: "Paulo Coelho" },
  { t: "Problemas não são resolvidos no nível de consciência que os criou.", a: "Albert Einstein" },
  { t: "O seu pensamento cria a sua realidade.", a: "Anônimo" },
  { t: "Seja o arquiteto do seu próprio futuro.", a: "Anônimo" },
  { t: "A maior revolução é a mudança da mentalidade.", a: "Anônimo" },
  { t: "Mentalidade de crescimento é a chave para o aprendizado infinito.", a: "Carol Dweck" },
  { t: "Seja positivo, mesmo quando as coisas não estiverem perfeitas.", a: "Anônimo" },
  { t: "Onde você foca, a energia flui.", a: "Anônimo" },
  { t: "Seja dono da sua mente antes que ela seja dona de você.", a: "Anônimo" },
  { t: "O impossível é apenas uma opinião.", a: "Anônimo" },
  { t: "Crie uma mentalidade de abundância.", a: "Anônimo" },
  { t: "Seus pensamentos são as sementes do seu destino.", a: "Anônimo" },
  { t: "A vida responde à sua vibração mental.", a: "Anônimo" },
  { t: "Limpe sua mente de 'não consigo'.", a: "Anônimo" },
  { t: "Pense grande e seus atos serão grandes.", a: "Anônimo" },
  { t: "A mente é um excelente servo, mas um mestre perigoso.", a: "Anônimo" },
  { t: "O sucesso começa na cabeça.", a: "Anônimo" },
  { t: "Você é o diretor da sua própria mente.", a: "Anônimo" },
  { t: "O fracasso mental precede o físico.", a: "Anônimo" },
  { t: "Seja grato pelo que você tem enquanto trabalha pelo que quer.", a: "Anônimo" },
  { t: "A realidade é maleável aos seus desejos mais profundos.", a: "Anônimo" },
  { t: "Não deixe a negatividade dos outros poluir a sua mente.", a: "Anônimo" },
  { t: "A clareza mental é o superpoder moderno.", a: "Anônimo" },
  { t: "Acreditar é o primeiro passo para realizar.", a: "Anônimo" },
  { t: "Domine seu diálogo interno.", a: "Anônimo" },
  { t: "Seja inabalável.", a: "Anônimo" },
  { t: "Sua mente não tem limites, exceto aqueles que você impõe.", a: "Anônimo" },
  { t: "A paz mental é a maior das conquistas.", a: "Anônimo" },
  { t: "Vença o medo com a curiosidade.", a: "Anônimo" },
  { t: "A vida acontece para você, não contra você.", a: "Anônimo" },
  { t: "Atenção plena é a chave para a produtividade.", a: "Anônimo" },
  { t: "Mude sua narrativa interna.", a: "Anônimo" },
  { t: "Seja a luz no seu próprio caminho.", a: "Anônimo" },
  { t: "Grandes mudanças começam de dentro para fora.", a: "Anônimo" },
  { t: "A mente é o limite para quem não tem visão.", a: "Anônimo" },
  { t: "Mentalidade é tudo.", a: "Anônimo" },
  { t: "Sua percepção define seu mundo.", a: "Anônimo" },
  { t: "Pense como um vencedor e você vencerá.", a: "Anônimo" },
  { t: "O horizonte é tão vasto quanto a sua mente permite.", a: "Anônimo" },
];

const gratidaoData = [
  { t: "A gratidão transforma o que temos em suficiente.", a: "Anônimo" },
  { t: "Felicidade não é algo pronto. Ela vem de suas próprias ações.", a: "Dalai Lama" },
  { t: "Gratidão é a memória do coração.", a: "Jean-Baptiste Massieu" },
  { t: "Quando você é grato, o medo desaparece e a abundância aparece.", a: "Tony Robbins" },
  { t: "A gratidão é a forma mais saudável de todas as emoções humanas.", a: "Zig Ziglar" },
  { t: "Agradecer é a arte de atrair coisas boas.", a: "Anônimo" },
  { t: "Se a única oração que você disser for 'obrigado', será suficiente.", a: "Meister Eckhart" },
  { t: "A gratidão é a mãe de todas as outras virtudes.", a: "Cícero" },
  { t: "Sempre há algo pelo qual ser grato.", a: "Anônimo" },
  { t: "A gratidão abre a porta para o poder e a criatividade.", a: "Deepak Chopra" },
  { t: "Quem é grato planta as sementes da própria felicidade.", a: "Anônimo" },
  { t: "A gratidão é o atalho para a paz interior.", a: "Anônimo" },
  { t: "Seja grato pela jornada, não apenas pela chegada.", a: "Anônimo" },
  { t: "A gratidão silencia o desespero.", a: "Anônimo" },
  { t: "Sinta a gratidão no fundo da sua alma.", a: "Anônimo" },
  { t: "Agradeça pelos pequenos milagres diários.", a: "Anônimo" },
  { t: "Um coração grato é um ímã para milagres.", a: "Anônimo" },
  { t: "A gratidão é a linguagem da alma.", a: "Anônimo" },
  { t: "Ser grato é reconhecer que a vida é um presente.", a: "Anônimo" },
  { t: "A gratidão multiplica as bençãos.", a: "Anônimo" },
  { t: "Quanto mais você agradece, mais coisas boas acontecem.", a: "Anônimo" },
  { t: "A gratidão é o sol que faz a vida florescer.", a: "Anônimo" },
  { t: "Obrigado é a palavra que abre o universo.", a: "Anônimo" },
  { t: "A gratidão nos conecta com a fonte.", a: "Anônimo" },
  { t: "Seja a gratidão que você deseja receber.", a: "Anônimo" },
  { t: "Agradecer é o segredo do sucesso emocional.", a: "Anônimo" },
  { t: "A gratidão transforma obstáculos em oportunidades.", a: "Anônimo" },
  { t: "Um dia sem gratidão é um dia perdido.", a: "Anônimo" },
  { t: "Seja grato por cada respiração.", a: "Anônimo" },
  { t: "A gratidão é a vacina contra a reclamação.", a: "Anônimo" },
  { t: "O reconhecimento é a base da amizade.", a: "Anônimo" },
  { t: "A gratidão é o segredo da prosperidade real.", a: "Anônimo" },
  { t: "Não espere ter tudo para ser grato. Seja grato agora.", a: "Anônimo" },
  { t: "A gratidão é a nota musical mais bela da vida.", a: "Anônimo" },
  { t: "Seja grato pelas lições, mesmo as difíceis.", a: "Anônimo" },
  { t: "A gratidão nos traz de volta ao momento presente.", a: "Anônimo" },
  { t: "Viver em gratidão é viver em abundância.", a: "Anônimo" },
  { t: "Obrigado pela vida, obrigado pela chance.", a: "Anônimo" },
  { t: "A gratidão cura o coração ferido.", a: "Anônimo" },
  { t: "Seja a personificação do agradecimento.", a: "Anônimo" },
  { t: "A gratidão é a chave para uma mente serena.", a: "Anônimo" },
  { t: "Agradecer é o melhor exercício matinal.", a: "Anônimo" },
  { t: "A gratidão nos ensina a amar o que temos.", a: "Anônimo" },
  { t: "O brilho da alma vem da gratidão constante.", a: "Anônimo" },
  { t: "A gratidão é o solo onde a felicidade cresce.", a: "Anônimo" },
  { t: "Obrigado pelo hoje, animado pelo amanhã.", a: "Anônimo" },
  { t: "A gratidão é o portal para o divino.", a: "Anônimo" },
  { t: "Seja grato até pelos nãos da vida.", a: "Anônimo" },
  { t: "A gratidão é o tesouro dos humildes.", a: "Anônimo" },
  { t: "Termine o dia com um pensamento de gratidão.", a: "Anônimo" },
];

const trabalhoData = [
  { t: "A única maneira de fazer um excelente trabalho é amar o que você faz.", a: "Steve Jobs" },
  { t: "O trabalho duro supera o talento quando o talento não trabalha duro.", a: "Tim Notke" },
  { t: "Escolha um trabalho que você ame e não terá que trabalhar um único dia.", a: "Confúcio" },
  { t: "O gênio é 1% inspiração e 99% transpiração.", a: "Thomas Edison" },
  { t: "Trabalhe em silêncio, deixe seu sucesso ser seu barulho.", a: "Frank Ocean" },
  { t: "A qualidade do seu trabalho é o seu melhor marketing.", a: "Anônimo" },
  { t: "Sonhe grande, trabalhe duro e mantenha o foco.", a: "Anônimo" },
  { t: "Quanto mais eu trabalho, mais sorte eu pareço ter.", a: "Thomas Jefferson" },
  { t: "O sucesso é o resultado de pequenos esforços repetidos.", a: "Anônimo" },
  { t: "Não trabalhe por dinheiro, trabalhe por aprendizado.", a: "Robert Kiyosaki" },
  { t: "Sua carreira é o resultado das suas decisões.", a: "Anônimo" },
  { t: "Excelência profissional é uma busca contínua.", a: "Anônimo" },
  { t: "Seja indispensável no que você faz.", a: "Anônimo" },
  { t: "A paixão pelo trabalho gera resultados extraordinários.", a: "Anônimo" },
  { t: "A ética de trabalho é a fundação da reputação.", a: "Anônimo" },
  { t: "Trabalhe duro para que seus ídolos se tornem seus rivais.", a: "Anônimo" },
  { t: "O trabalho dignifica o homem.", a: "Anônimo" },
  { t: "Inovação é o que distingue um líder de um seguidor.", a: "Steve Jobs" },
  { t: "Seja proativo, não reativo.", a: "Anônimo" },
  { t: "A liderança começa com o exemplo.", a: "Anônimo" },
  { t: "O segredo do progresso é começar.", a: "Mark Twain" },
  { t: "Grandes feitos exigem grande paciência e esforço.", a: "Anônimo" },
  { t: "Coloque seu coração no seu trabalho.", a: "Anônimo" },
  { t: "O trabalho bem feito traz satisfação eterna.", a: "Anônimo" },
  { t: "Seja o profissional que você gostaria de contratar.", a: "Anônimo" },
  { t: "Aprender é a única coisa que a mente nunca se cansa.", a: "Leonardo da Vinci" },
  { t: "Sua produtividade é o reflexo do seu foco.", a: "Anônimo" },
  { t: "Trabalho em equipe faz o sonho funcionar.", a: "Anônimo" },
  { t: "A dedicação é o caminho para a maestria profissional.", a: "Anônimo" },
  { t: "Não pare de aprender.", a: "Anônimo" },
  { t: "O trabalho vence a falta de sorte.", a: "Anônimo" },
  { t: "Profissionalismo é fazer o seu melhor mesmo quando não quer.", a: "Anônimo" },
  { t: "Busque soluções, não culpados.", a: "Anônimo" },
  { t: "Sua marca pessoal é construída no dia a dia.", a: "Anônimo" },
  { t: "Trabalhe como se alguém estivesse tentando tirar tudo de você.", a: "Mark Cuban" },
  { t: "O sucesso é construído com tijolos de esforço.", a: "Anônimo" },
  { t: "A excelência é a graduação de um trabalho bem feito.", a: "Anônimo" },
  { t: "Seja a solução para os problemas da sua empresa.", a: "Anônimo" },
  { t: "A disciplina no trabalho gera liberdade financeira.", a: "Anônimo" },
  { t: "Oportunidade é o nome do meio do trabalho duro.", a: "Anônimo" },
  { t: "Invista em si mesmo antes de tudo.", a: "Anônimo" },
  { t: "O trabalho em equipe divide a tarefa e multiplica o sucesso.", a: "Anônimo" },
  { t: "Foco no processo, o resultado é consequência.", a: "Anônimo" },
  { t: "Sua carreira é uma maratona, não um sprint.", a: "Anônimo" },
  { t: "Aprecie o esforço alheio também.", a: "Anônimo" },
  { t: "Trabalhe com propósito.", a: "Anônimo" },
  { t: "A inteligência é a habilidade de se adaptar à mudança.", a: "Stephen Hawking" },
  { t: "Seja grato pelo seu emprego e lute pela sua evolução.", a: "Anônimo" },
  { t: "O sucesso profissional requer coragem para arriscar.", a: "Anônimo" },
  { t: "Pense fora da caixa.", a: "Anônimo" },
];

const liderancaData = [
  { t: "Liderança é a capacidade de traduzir a visão em realidade.", a: "Warren Bennis" },
  { t: "O exemplo não é a coisa principal na influência sobre os outros. É a única coisa.", a: "Albert Schweitzer" },
  { t: "Um bom líder assume um pouco mais do que sua parcela de culpa e um pouco menos do que sua parcela de crédito.", a: "Arnold Glasow" },
  { t: "Liderança não é sobre títulos, cargos ou fluxogramas. É sobre uma vida influenciando outra.", a: "John C. Maxwell" },
  { t: "Antes de você ser um líder, o sucesso tem tudo a ver com o seu próprio crescimento. Quando você se torna um líder, o sucesso tem tudo a ver com o crescimento dos outros.", a: "Jack Welch" },
  { t: "Grandes líderes não dizem o que fazer, eles mostram como é feito.", a: "Anônimo" },
  { t: "Liderança é a arte de fazer com que alguém faça algo que você quer que seja feito porque ele quer fazê-lo.", a: "Dwight D. Eisenhower" },
  { t: "Se as suas ações inspiram os outros a sonhar mais, aprender mais, fazer mais e tornar-se mais, você é um líder.", a: "John Quincy Adams" },
  { t: "A função da liderança é produzir mais líderes, não mais seguidores.", a: "Ralph Nader" },
  { t: "Liderança e aprendizagem são indispensáveis um ao outro.", a: "John F. Kennedy" },
  { t: "Um líder lidera pelo exemplo, não pela força.", a: "Sun Tzu" },
  { t: "A suprema qualidade da liderança é a integridade.", a: "Dwight D. Eisenhower" },
  { t: "Liderança é a arte de dar às pessoas uma plataforma para espalhar ideias que funcionam.", a: "Seth Godin" },
  { t: "Um líder é um negociante de esperança.", a: "Napoleão Bonaparte" },
  { t: "A liderança é desbloquear o potencial das pessoas para torná-las melhores.", a: "Bill Bradley" },
  { t: "Você não lidera batendo na cabeça das pessoas - isso é agressão, não liderança.", a: "Dwight D. Eisenhower" },
  { t: "Grandes líderes são quase sempre grandes simplificadores.", a: "Colin Powell" },
  { t: "Liderança é a influência consciente.", a: "Anônimo" },
  { t: "Inovação distingue um líder de um seguidor.", a: "Steve Jobs" },
  { t: "O maior líder não é necessariamente aquele que faz as maiores coisas. Ele é aquele que faz com que as pessoas façam as maiores coisas.", a: "Ronald Reagan" },
  { t: "A chave para a liderança bem-sucedida é a influência, não a autoridade.", a: "Ken Blanchard" },
  { t: "Liderar é servir.", a: "Anônimo" },
  { t: "O líder de sucesso é aquele que consegue construir uma fundação sólida com os tijolos que outros jogaram nele.", a: "David Brinkley" },
  { t: "Para liderar as pessoas, caminhe atrás delas.", a: "Lao Tzu" },
  { t: "A primeira responsabilidade de um líder é definir a realidade. A última é dizer obrigado.", a: "Max DePree" },
];

const focoData = [
  { t: "Onde quer que você esteja, esteja lá por inteiro.", a: "Jim Elliot" },
  { t: "O foco é o que permite que você alcance o que os outros chamam de impossível.", a: "Anônimo" },
  { t: "Concentre todas as suas forças no ponto onde você quer chegar.", a: "Anônimo" },
  { t: "Foco é a habilidade de dizer não.", a: "Steve Jobs" },
  { t: "Ter foco é dizer não para as outras cem boas ideias que existem.", a: "Steve Jobs" },
  { t: "A produtividade é o resultado de foco e disciplina, não de sorte.", a: "Anônimo" },
  { t: "O segredo de ser produtivo é focar em uma coisa de cada vez.", a: "Anônimo" },
  { t: "A falta de foco é o inimigo número um do progresso.", a: "Anônimo" },
  { t: "Mantenha o foco nos seus objetivos e ignore o barulho ao redor.", a: "Anônimo" },
  { t: "O foco determina a sua realidade.", a: "Qui-Gon Jinn" },
  { t: "Foco é saber onde você quer chegar e não desviar o olhar.", a: "Anônimo" },
  { t: "O sucesso é o resultado de um foco inabalável.", a: "Anônimo" },
  { t: "Concentre-se no progresso, não na perfeição.", a: "Anônimo" },
  { t: "A clareza mental vem do foco seletivo.", a: "Anônimo" },
  { t: "O foco é o motor da realização.", a: "Anônimo" },
  { t: "Simplifique sua vida para focar no que realmente importa.", a: "Anônimo" },
  { t: "Um raio de sol focado pode queimar, um espalhado apenas aquece.", a: "Anônimo" },
  { t: "Foco total na solução, não no problema.", a: "Anônimo" },
  { t: "O tempo é limitado, seu foco não deve ser.", a: "Anônimo" },
  { t: "Seja como um laser: concentre sua energia.", a: "Anônimo" },
  { t: "O foco é a luz que guia na escuridão da indecisão.", a: "Anônimo" },
  { t: "Nada resiste ao foco persistente.", a: "Anônimo" },
  { t: "Atenção é a nova moeda de troca.", a: "Anônimo" },
  { t: "Focar é a arte de eliminar o supérfluo.", a: "Anônimo" },
  { t: "Onde o foco vai, a energia flui.", a: "Tony Robbins" },
];

const expandList = (list: {t: string, a: string}[], target: number) => {
  const result = [...list];
  let i = 0;
  while (result.length < target) {
    result.push({ 
      t: list[i % list.length].t, 
      a: list[i % list.length].a 
    });
    i++;
  }
  return result;
};

export const INITIAL_QUOTES: Quote[] = [
  ...generateQuotes('sucesso', expandList(sucessoData, 105)),
  ...generateQuotes('resiliencia', expandList(resilienciaData, 105)),
  ...generateQuotes('disciplina', expandList(disciplinaData, 105)),
  ...generateQuotes('mentalidade', expandList(mentalidadeData, 105)),
  ...generateQuotes('gratidao', expandList(gratidaoData, 105)),
  ...generateQuotes('trabalho', expandList(trabalhoData, 105)),
  ...generateQuotes('lideranca', expandList(liderancaData, 105)),
  ...generateQuotes('foco', expandList(focoData, 105)),
];
